# Generated by Django 3.2 on 2021-05-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ex',
            name='mm',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ex',
            name='year',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
