# Generated by Django 3.2 on 2021-05-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20210513_0453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ex',
            new_name='exer',
        ),
    ]
